// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `user_info` table.
    ///
    /// (Automatically generated by Diesel.)
    user_info (id, username) {
        /// The `id` column of the `user_info` table.
        ///
        /// Its SQL type is `Unsigned<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Unsigned<Integer>,
        /// The `username` column of the `user_info` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        username -> Varchar,
        /// The `header_url` column of the `user_info` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        header_url -> Varchar,
        /// The `ch3` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        ch3 -> Double,
        /// The `ch4` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        ch4 -> Double,
        /// The `ch5` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        ch5 -> Double,
        /// The `ch6` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        ch6 -> Double,
        /// The `ch8` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        ch8 -> Double,
        /// The `total` column of the `user_info` table.
        ///
        /// Its SQL type is `Double`.
        ///
        /// (Automatically generated by Diesel.)
        total -> Double,
        /// The `pass_time` column of the `user_info` table.
        ///
        /// Its SQL type is `Bigint`.
        ///
        /// (Automatically generated by Diesel.)
        pass_time -> Bigint,
    }
}
